#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SDL_ttf
Version  : 2.0.11
Release  : 16
URL      : https://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11.tar.gz
Summary  : Simple DirectMedia Layer - Sample TrueType Font Library
Group    : Development/Tools
License  : FTL Zlib
Requires: SDL_ttf-lib = %{version}-%{release}
Requires: SDL_ttf-license = %{version}-%{release}
BuildRequires : mesa-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(sdl)

%description
This library allows you to use TrueType fonts to render text in SDL
applications.

%package dev
Summary: dev components for the SDL_ttf package.
Group: Development
Requires: SDL_ttf-lib = %{version}-%{release}
Provides: SDL_ttf-devel = %{version}-%{release}
Requires: SDL_ttf = %{version}-%{release}

%description dev
dev components for the SDL_ttf package.


%package lib
Summary: lib components for the SDL_ttf package.
Group: Libraries
Requires: SDL_ttf-license = %{version}-%{release}

%description lib
lib components for the SDL_ttf package.


%package license
Summary: license components for the SDL_ttf package.
Group: Default

%description license
license components for the SDL_ttf package.


%prep
%setup -q -n SDL_ttf-2.0.11
cd %{_builddir}/SDL_ttf-2.0.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600307100
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1600307100
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL_ttf
cp %{_builddir}/SDL_ttf-2.0.11/COPYING %{buildroot}/usr/share/package-licenses/SDL_ttf/2cafb05735e4e35d5d08007685cecf572cd4558b
cp %{_builddir}/SDL_ttf-2.0.11/VisualC/external/lib/x64/LICENSE.freetype.txt %{buildroot}/usr/share/package-licenses/SDL_ttf/9848eb36a6f028abb46ba30f7f6336b1e7062b28
cp %{_builddir}/SDL_ttf-2.0.11/VisualC/external/lib/x64/LICENSE.zlib.txt %{buildroot}/usr/share/package-licenses/SDL_ttf/0589d4998a3640a7e208f6e560264e70a2cb5b19
cp %{_builddir}/SDL_ttf-2.0.11/VisualC/external/lib/x86/LICENSE.freetype.txt %{buildroot}/usr/share/package-licenses/SDL_ttf/9848eb36a6f028abb46ba30f7f6336b1e7062b28
cp %{_builddir}/SDL_ttf-2.0.11/VisualC/external/lib/x86/LICENSE.zlib.txt %{buildroot}/usr/share/package-licenses/SDL_ttf/0589d4998a3640a7e208f6e560264e70a2cb5b19
cp %{_builddir}/SDL_ttf-2.0.11/Xcode/Frameworks/FreeType.framework/LICENSE.freetype.txt %{buildroot}/usr/share/package-licenses/SDL_ttf/9848eb36a6f028abb46ba30f7f6336b1e7062b28
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL/SDL_ttf.h
/usr/lib64/libSDL_ttf.so
/usr/lib64/pkgconfig/SDL_ttf.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL_ttf-2.0.so.0
/usr/lib64/libSDL_ttf-2.0.so.0.10.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL_ttf/0589d4998a3640a7e208f6e560264e70a2cb5b19
/usr/share/package-licenses/SDL_ttf/2cafb05735e4e35d5d08007685cecf572cd4558b
/usr/share/package-licenses/SDL_ttf/9848eb36a6f028abb46ba30f7f6336b1e7062b28
